//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bhclass
    {
        public int id { get; set; }
        public Nullable<int> timeslotId { get; set; }
        public Nullable<int> teacherId { get; set; }
        public Nullable<int> classroomId { get; set; }
        public Nullable<int> courseId { get; set; }
        public Nullable<decimal> fee { get; set; }
        public string semester { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> modifiedAt { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
