//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_student
    {
        public int id { get; set; }
        public int classId { get; set; }
        public int studentId { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> modifiedAt { get; set; }
        public string modifiedBy { get; set; }
    }
}
