//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class classroom
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> capacity { get; set; }
        public string function { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> createAt { get; set; }
        public Nullable<System.DateTime> modifiedAt { get; set; }
        public string modifiedBy { get; set; }
    }
}
