//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public int id { get; set; }
        public string name { get; set; }
        public string textbook { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> modifiedAt { get; set; }
        public Nullable<decimal> textbookFee { get; set; }
        public Nullable<int> minAge { get; set; }
    }
}
