//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int id { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public Nullable<int> imageId { get; set; }
        public Nullable<int> ownerId { get; set; }
        public string status { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
    }
}
