//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int id { get; set; }
        public Nullable<int> householdId { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string chineseName { get; set; }
        public string type { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> modifiedAt { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string createdBy { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public string phone { get; set; }
        public System.DateTime born { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
