//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int id { get; set; }
        public int memberId { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string description { get; set; }
        public System.DateTime updatedAt { get; set; }
        public string updatedBy { get; set; }
        public string status { get; set; }
    }
}
